apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  namespace: devops
  labels:
    app: wordpress
    tier: frontend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.142
    # Exported path of your NFS server
    path: "/dados/devops"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  namespace: devops
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.142
    # Exported path of your NFS server
    path: "/dados/devops"
